### ISSUE TITLE
`ant` failed to build on MacOS Mojave `10.14.1`

### ISSUE THREAD

**Issue by mohnjatthews** [aionnetwork/AVM#324]
When running `ant` after cloning the AVM repo, the terminal outputs the following:

```bash

...

BUILD FAILED
/Users/john/Code/AVM/build.xml:60: Warning: Could not find file /Users/john/Code/AVM/LICENSE to copy.
```

Renaming `LICENSE.txt` to `LICENSE` fixes the issue.

```bash
mv LICENSE.txt LICENSE
```

OS: MacOS Mojave `10.14.1`
Ant: `1.10.5`

**Comment by jeff-aion** [comment]
This is just more fall-out from me forgetting that this is directly referenced from other processes, not just being added to the repo.  I want to double-check that this packaging step still actually makes sense.
