### ISSUE TITLE
Provide Maven Build and Publish AVM Artefact

### ISSUE THREAD

**Issue by lazaridiscom** [aionnetwork/AVM#366]
(related #365)

## Problem

The current ~build~ build-test via `ant test` does not work e.g. on native windows, as it uses `./compile.sh` (see #365).

It would be preferable to build the project via a usual maven setup, and publish the artifact to a repository.

EDIT: corrected after getting the clarifying reply.

**Comment by jeff-aion** [comment]
This isn't an `ant` problem, it is that one of our tests run in the `ant` build calls a shell script which isn't intended for Windows.  Part of the reason we aren't changing our build system is that losing the ability to run tests like that won't improve quality.

It is part of the issue of `compile.sh` having lived longer than we thought it would.  It was only intended to be stop-gap until other tools were available but we are still mostly maintaining/testing it.

The publication of built resources is a different matter than build systems.  This is more a question of how we are factoring the system and what embeddable components should be pushed and at what cadence.

**Comment by lazaridiscom** [comment]
my fault `compile.sh`.

still, it would be preferable to have a publish artefact, as usual within java (simply because seasoned java devs will expect this).

**Comment by lazaridiscom** [comment]
> it is that one of our tests run in the ant build calls a shell script which isn't intended for Windows. Part of the reason we aren't changing our build system is that losing the ability to run tests like that won't improve quality.

You do not have quality, if your java-code is not cross-platform.

(Me aborting at this point, as I'm bound to evaluate Win&Lin. And be assured that other evaluators abort too, they just don't tell you)

**Comment by lazaridiscom** [comment]
See https://github.com/aionnetwork/AVM/issues/365#issuecomment-470211550 for a workaround to use the existent build-system on windows.

(closing this for now, but you should at some point publish an avm artefact)
