### ISSUE TITLE
Restrict scope of intial release shadow JCL scope

### ISSUE THREAD

**Issue by jeff-aion** [aionnetwork/AVM#371]
Earlier, we were attempting to contain the entire scope of any classes we wanted to support in the shadow JCL.  Some omissions were required, earlier on, due to:  references to classes not supported (ie `Stream`) or functionality which was incompatible with the blockchain (ie `Math.random()`).

This still leaves a very large surface area which must be tested and secured, despite probably not being relevant to the blockchain contracts (consider all that `Character` can do regarding specialized unicode parsing, for instance).

Instead, this item will track any discussion around changing our philosophy to assume exclusion from the AVM shadow JCL, unless a case can be made for why a given method _should_ be included.

It is a safer position to start with a restricted library and only open that up in future hard-forks instead of risk inconsistencies or errors due to exposing a large class library which couldn't be as exhaustively tested.

**Comment by jeff-aion** [comment]
Note that we should also do a basic audit of whether we correctly map/handle all the exceptions thrown from the underlying JDK calls while verifying what is left in scope.

**Comment by aion-shidokht** [comment]
During the review, usage of internal methods in final classes should be evaluated.
