### ISSUE TITLE
Update API docs HTML to link to underlying source

### ISSUE THREAD

**Issue by fulldecent** [aionnetwork/AVM#393]
Files in this repository are being built to produce https://github.com/aionnetwork/avm-api-docs

The theme used can be updated so that each function/parameter/etc in the build documentation will link to the original file on GitHub.

This will allow easier workflow for editing built documentation. The new workflow will be:

1. Somebody reads documentation at XXXXURL
2. Identify typo/issue
3. Click the link
4. Fork, edit the original file on AVM repository, PR
5. PR merged, documentation rebuild, deployed

**Comment by fulldecent** [comment]
Typo: Edit on Github -> Edit on GitHub

**Comment by jeff-aion** [comment]
You will need to open this issue against that project since it purely downstream of AVM (the docs team owns that tooling and process - it isn't part of the AVM implementation).
