### ISSUE TITLE
Why are addresses 32 bytes?

### ISSUE THREAD

**Issue by fulldecent** [aionnetwork/AVM#397]
Addresses are specified in code as 32 bytes https://github.com/aionnetwork/AVM/blob/master/org.aion.avm.api/src/avm/Address.java#L11

But documentation for FastVM states addresses are 128-bits. Documentation for AVM does not specify bit length.

**Comment by jeff-aion** [comment]
Where does the FastVM doc state that the addresses are 128-bit?  Here, it defines them as 32 bytes:  https://github.com/aionnetwork/aion_fastvm/wiki/Specifications

This isn't specific to either VM but a defined constant of the Aion network.

**Comment by fulldecent** [comment]
Thank you. I was confused with FastVM documentation. No problem here.
